import Link from 'next/link';
import './globals.css';
import Header from './components/Header';
import Footer from './components/Footer';

export const metadata = {
  title: 'Micropromotions',
  description: 'Music reviews made easy',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {/* Uncomment the following section if you want a static header */}
        {/* <header className="bg-white shadow px-6 py-4 flex justify-between items-center">
          <a href="/" className="text-2xl font-bold text-black">SmashHaus</a>
          <nav className="flex gap-6 text-sm font-medium text-gray-600">
            <a href="/payer/dashboard" className="hover:text-black">Dashboard</a>
            <a href="/payer/upload" className="hover:text-black">Upload</a>
            <a href="/worker/dashboard" className="hover:text-black">Worker View</a>
          </nav>
        </header> */}
        <main className="pt-[80px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
